name: Matrix Test Suite
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test matrix strategy
    strategy:
      matrix:
        node-version: [18,20,22]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: print status
        run: echo "Running tests on ${{ matrix.os }} with Node ${{ matrix.node-version }}"